### ISSUE TITLE
Error when clicking empty spaces/background

### ISSUE THREAD

**Issue by psociety** [mathishouis/scuti-renderer#29]
```
RoomCamera.ts:175 Uncaught TypeError: Cannot read properties of undefined (reading 'emit')
    at HTMLCanvasElement._tilePointerDown (RoomCamera.ts:175:81)

RoomCamera.ts:185 Uncaught TypeError: Cannot read properties of undefined (reading 'emit')
    at HTMLCanvasElement._tilePointerUp (RoomCamera.ts:185:81)
```

**Comment by psociety** [comment]
This also got fixed on https://github.com/kozennnn/scuti-renderer/pull/32 so i close it
